# Introduction to NumPy

## Exercises:

### 1. Update/Upgrade the NumPy package to the latest version

In [ ]:
# Parts 1 and 2 can be executed in Jupyter or the Anacodna Prompt

### 2. Install/Upgrade another package (e.g. Pandas) 

In [1]:
pip install panda --upgrade

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.

  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for panda: filename=panda-0.3.1-py3-none-any.whl size=7245 sha256=13ac6e5ff2e4ab114914851a3ddbdcb6334c62fedb5fb5caedbfa7e57f122797
  Stored in directory: c:\users\ikenna george\appdata\local\pip\cache\wheels\98\41\5b\6ca54e0b6a35e1b7248c12f56fcb753dfb7717fefaa0fb45f5
Successfully built panda


### 3. Import NumPy as <i> np </i>

In [2]:
import numpy as np

### 4. Use the<i> np.array() </i>function to create an array variable - <i>array_hw_1</i> with the numbers 4,5,7 and 10 in it

In [3]:
array_hw_1 = np.array([4,5,7,10])

### 5. Display the new array on screen

In [4]:
array_hw_1

array([ 4,  5,  7, 10])

### 6. Create a 2x2 array with the same values as <i> array_hw_1 </i> and display it on the screen

In [6]:
array_hw_2 = np.array([[4,5],[7,10]])

In [7]:
array_hw_2

array([[ 4,  5],
       [ 7, 10]])

### 7. Call the <i> np.mean() </i> function on each array

In [8]:
np.mean(array_hw_1)

np.float64(6.5)

### 8. Use the <i> axis </i> argument to find the mean for all the rows of <i> array_hw_2</i>

In [9]:
np.mean(array_hw_2)

np.float64(6.5)

### 9. Use the <i>axis</i> argument to find the mean for all the columns of <i>array_hw_2</i>

In [27]:
np.mean(array_hw_2, axis = 0)

array([5.5, 7.5])

### 10. Use the <i> Shift + Tab </i> shorcut on <i> np.mean() </i> to check what possible arguments we can specify. 

### 11. Set the <i> dtype </i> argument equal to <i> np.int </i> and compare the results 

In [28]:
np.mean(array_hw_2, axis = 0),( dtype = np.int)

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (1423220002.py, line 1)