In [23]:
import numpy as np

In [24]:
array_a = np.array([1,2,3])

In [25]:
array_a

array([1, 2, 3])

In [26]:
array_b = np.array([[1,2,3],[4,5,6]])
array_b

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
array_hw_1 = np.array([4,6,7,10])

In [28]:
array_hw_1

array([ 4,  6,  7, 10])

In [29]:
m = np.array([[5,12,6],[-3,0,14]])

In [30]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])